program: training/train.py
method: bayes
metric:
  name: val_acc
  goal: maximize
parameters:
    # Fixed parameters
  epochs:
    value: 10
  batch-size:
    value: 32
  num-classes:
    value: 10

  # Hyperparameters to be tuned
  frozen-blocks:
    distribution: int_uniform
    min: 0
    max: 4
  learning-rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3
  decay:
    distribution: log_uniform_values
    min: 0.1
    max: 10.0
  input-shape:
    values: [
      [128,128],
      [480,640],
      [224,224],
      [300,300],
      [350,400],
      [400,400],
      [450,500],
      [500,500]
    ]
  brightness:
    distribution: log_uniform_values
    min: 0.01
    max: 1.0
  contrast:
    distribution: log_uniform_values
    min: 0.01
    max: 1.0
  saturation:
    distribution: log_uniform_values
    min: 0.01
    max: 1.0